# Generated by Django 5.0.14 on 2026-02-10 18:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=255, null=True)),
                ("location_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("more_details_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="core.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="events_even_date_5e8e1c_idx"),
                    models.Index(
                        fields=["location"], name="events_even_locatio_0ae1f4_idx"
                    ),
                ],
            },
        ),
    ]
