# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorsPick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location_tag",
                    models.CharField(
                        db_index=True,
                        help_text="Location scope for this pick (e.g., 'nairobi', 'mombasa')",
                        max_length=100,
                    ),
                ),
                ("active_from", models.DateTimeField(help_text="When this pick becomes active")),
                ("active_until", models.DateTimeField(help_text="When this pick expires")),
                (
                    "curator_note",
                    models.TextField(help_text="Required editorial note explaining why this event is featured"),
                ),
                (
                    "curator_name",
                    models.CharField(
                        blank=True,
                        default="Pursuit team",
                        help_text="Attribution for the curator (e.g., 'Pursuit team', 'Jane Doe')",
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Reserved for future multi-pick surfaces; v1 always uses position=1"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Editor's Pick",
                "verbose_name_plural": "Editor's Picks",
                "ordering": ["-active_from", "position"],
            },
        ),
        migrations.CreateModel(
            name="UserEvents",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User's Saved Event",
                "verbose_name_plural": "User's Saved Events",
                "db_table": "users_user_events",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=255, null=True)),
                ("location_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                ("more_details_url", models.URLField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Ticket price in KES. 0 for free events.", max_digits=10
                    ),
                ),
                (
                    "ticketing_enabled",
                    models.BooleanField(
                        default=False, help_text="True if tickets are sold in-app. False if event links externally."
                    ),
                ),
                (
                    "available_tickets",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Remaining ticket count. Null for free or externally ticketed events.",
                        null=True,
                    ),
                ),
                (
                    "going_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of users who have saved or are attending."
                    ),
                ),
                (
                    "has_gallery",
                    models.BooleanField(default=False, help_text="True if this event has a gallery of images."),
                ),
                (
                    "gallery_images",
                    models.JSONField(blank=True, default=list, help_text="List of image URLs for the event gallery."),
                ),
                (
                    "gallery_description",
                    models.TextField(blank=True, help_text="Description of the gallery content.", null=True),
                ),
                (
                    "series_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the recurring series this event belongs to. e.g. 'Blankets & Wine'. Soft reference only — no FK. Full series model is V2.",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("live", "Live"), ("cancelled", "Cancelled"), ("ended", "Ended")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.ManyToManyField(blank=True, related_name="events", to="core.category")),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["date"],
            },
        ),
    ]
