# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="events", to="organizers.organizerprofile"
            ),
        ),
        migrations.AddField(
            model_name="editorspick",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="editors_picks", to="events.event"
            ),
        ),
        migrations.AddField(
            model_name="userevents",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_interactions", to="events.event"
            ),
        ),
    ]
