# Generated by Django 5.0.14 on 2026-02-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_location_name_alter_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
    ]
