# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userevents",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="saved_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="events_even_date_5e8e1c_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["location"], name="events_even_locatio_0ae1f4_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_active", "date"], name="events_even_is_acti_85e9ee_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_free", "date"], name="events_even_is_free_03365a_idx"),
        ),
        migrations.AddIndex(
            model_name="editorspick",
            index=models.Index(fields=["location_tag", "active_from"], name="events_edit_locatio_e26739_idx"),
        ),
        migrations.AddIndex(
            model_name="editorspick",
            index=models.Index(fields=["active_from", "active_until"], name="events_edit_active__770025_idx"),
        ),
        migrations.AddIndex(
            model_name="userevents",
            index=models.Index(fields=["user"], name="users_user__user_id_2ea0ce_idx"),
        ),
        migrations.AddIndex(
            model_name="userevents",
            index=models.Index(fields=["event"], name="users_user__event_i_2e78aa_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userevents",
            unique_together={("user", "event")},
        ),
    ]
