# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_is_active"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_active", "date"], name="events_even_is_acti_date_idx"),
        ),
    ]
