# Generated by Django 5.0.14 on 2026-06-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('available', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_tiers', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Tier',
                'verbose_name_plural': 'Ticket Tiers',
                'ordering': ['sort_order', 'price'],
                'unique_together': {('event', 'name')},
            },
        ),
    ]
