# Generated by Django 5.0.14 on 2026-02-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_is_active_date_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_is_acti_85e9ee_idx",
            old_name="events_even_is_acti_date_idx",
        ),
    ]
