# Generated by Django 5.0.14 on 2026-02-27 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_rename_events_even_is_acti_date_idx_events_even_is_acti_85e9ee_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEvents",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_interactions", to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User's Saved Event",
                "verbose_name_plural": "User's Saved Events",
                "db_table": "users_user_events",
                "indexes": [
                    models.Index(fields=["user"], name="users_user__user_id_2ea0ce_idx"),
                    models.Index(fields=["event"], name="users_user__event_i_2e78aa_idx"),
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
