# Generated by Django 5.0.14 on 2026-02-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_emoji_rename_emoji_category_icon"),
        ("events", "0005_userevents"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_free", "date"], name="events_even_is_free_03365a_idx"),
        ),
    ]
