# Generated by Django 5.0.14 on 2026-06-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_organizer_remove_is_free_index'),
        ('organizers', '0004_alter_organizerprofile_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Event organizer (cannot delete organizer with events)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizers.organizerprofile'),
        ),
    ]
