# Generated by Django 5.0.14 on 2026-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_free_event_events_even_is_free_03365a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='curator_name',
            field=models.CharField(blank=True, help_text="Attribution for the curator note, e.g. 'Pursuit team'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='curator_note',
            field=models.TextField(blank=True, help_text="Optional editorial note for featured/editor's pick events", null=True),
        ),
    ]
