# Generated by Django 5.0.14 on 2026-06-15 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_organizer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventGoing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="going_users", to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="going_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Going",
                "verbose_name_plural": "Events Going",
                "db_table": "events_event_going",
                "indexes": [
                    models.Index(fields=["user", "event"], name="events_even_user_id_e30657_idx"),
                    models.Index(fields=["user", "-created_at"], name="events_even_user_id_84aa63_idx"),
                    models.Index(fields=["event"], name="events_even_event_i_94997f_idx"),
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
