# Generated by Django 5.0.14 on 2026-05-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_add_curator_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorsPick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location_tag",
                    models.CharField(
                        db_index=True,
                        help_text="Location scope for this pick (e.g., 'nairobi', 'mombasa')",
                        max_length=100,
                    ),
                ),
                ("active_from", models.DateTimeField(help_text="When this pick becomes active")),
                ("active_until", models.DateTimeField(help_text="When this pick expires")),
                (
                    "curator_note",
                    models.TextField(help_text="Required editorial note explaining why this event is featured"),
                ),
                (
                    "curator_name",
                    models.CharField(
                        blank=True,
                        default="Pursuit team",
                        help_text="Attribution for the curator (e.g., 'Pursuit team', 'Jane Doe')",
                        max_length=100,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Reserved for future multi-pick surfaces; v1 always uses position=1"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="editors_picks", to="events.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor's Pick",
                "verbose_name_plural": "Editor's Picks",
                "ordering": ["-active_from", "position"],
                "indexes": [
                    models.Index(fields=["location_tag", "active_from"], name="events_edit_locatio_e26739_idx"),
                    models.Index(fields=["active_from", "active_until"], name="events_edit_active__770025_idx"),
                ],
            },
        ),
    ]
