# Generated by Django 5.0.14 on 2026-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_editorspick"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="curator_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="curator_note",
        ),
    ]
