# Generated by Django 5.0.14 on 2026-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_remove_event_curator_name_remove_event_curator_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="available_tickets",
            field=models.PositiveIntegerField(
                blank=True, help_text="Remaining ticket count. Null for free or externally ticketed events.", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="gallery_description",
            field=models.TextField(blank=True, help_text="Description of the gallery content.", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list, help_text="List of image URLs for the event gallery."),
        ),
        migrations.AddField(
            model_name="event",
            name="going_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of users who have saved or are attending."),
        ),
        migrations.AddField(
            model_name="event",
            name="has_gallery",
            field=models.BooleanField(default=False, help_text="True if this event has a gallery of images."),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Ticket price in KES. 0 for free events.", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="series_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the recurring series this event belongs to. e.g. 'Blankets & Wine'. Soft reference only — no FK. Full series model is V2.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ticketing_enabled",
            field=models.BooleanField(
                default=False, help_text="True if tickets are sold in-app. False if event links externally."
            ),
        ),
    ]
