# Generated by Django 5.0.14 on 2025-12-01 13:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
                "db_table": "users_interests",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(max_length=500, unique=True)),
                ("device_info", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Device Session",
                "verbose_name_plural": "Device Sessions",
                "db_table": "users_device_session",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_google__98b509_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_created_cf865c_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_completed_onboarding",
        ),
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_reset_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="instagram_username",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitter_username",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("email", "Email"), ("google", "Google SSO")],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of verification token",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of reset token",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="provider_id",
            field=models.CharField(
                blank=True,
                help_text="ID from the authentication provider",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_integrated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_provider",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("google_calendar", "Google Calendar"),
                    ("outlook", "Microsoft Outlook"),
                    ("apple_calendar", "Apple Calendar"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_sync_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_billing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("premium", "Premium")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="search_radius_km",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Default search radius for nearby events in kilometers",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("auto", "Auto")],
                default="auto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(blank=True, default="UTC", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="City, State/Country display name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["provider_id"], name="users_user_provide_8a3e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["auth_provider"], name="users_user_auth_pr_06709b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="users_user_date_jo_064c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interest",
            index=models.Index(fields=["name"], name="users_inter_name_172fbf_idx"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's selected interests for personalization",
                related_name="users",
                to="users.interest",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to="users.usersession",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="users_devic_user_id_fb739d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["created_at"], name="users_devic_created_8e198b_idx"
            ),
        ),
    ]
