# Generated by Django 4.2.16 on 2025-11-25 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("unicode_value", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Emoji",
                "verbose_name_plural": "Emojis",
                "db_table": "core_emoji",
                "ordering": ["category", "description"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="core_emoji_categor_54642a_idx"
                    ),
                    models.Index(
                        fields=["symbol"], name="core_emoji_symbol_e539bc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#007AFF", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "core_category",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="core_catego_name_6ef604_idx"),
                    models.Index(
                        fields=["is_active"], name="core_catego_is_acti_26a709_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="core_catego_sort_or_9f1e28_idx"
                    ),
                ],
            },
        ),
    ]
