# Generated by Django 5.0.14 on 2026-06-04 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#007AFF", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "core_category",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="core_catego_name_6ef604_idx"),
                    models.Index(fields=["is_active"], name="core_catego_is_acti_26a709_idx"),
                    models.Index(fields=["sort_order"], name="core_catego_sort_or_9f1e28_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interests",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
                "db_table": "users_interests",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="users_inter_name_172fbf_idx")],
            },
        ),
    ]
