# Generated by Django 5.0.14 on 2026-06-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Only one config should be active at a time"),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Platform fee percentage (e.g., 2.00 for 2%)",
                        max_digits=5,
                    ),
                ),
                (
                    "min_payout_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=100.0,
                        help_text="Minimum payout amount in KES (future use)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_ticket_quantity",
                    models.PositiveIntegerField(default=10, help_text="Maximum tickets per order (future use)"),
                ),
                (
                    "order_expiration_minutes",
                    models.PositiveIntegerField(default=15, help_text="Minutes until pending order expires"),
                ),
                (
                    "payout_delay_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Hours to wait after payment before processing payout"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who last updated config",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Configuration",
                "verbose_name_plural": "Platform Configurations",
                "db_table": "core_platform_config",
                "ordering": ["-created_at"],
            },
        ),
    ]
