# Generated by Django 5.0.14 on 2026-06-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_platformconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly slug (e.g., 'talks-and-ideas')",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
