# Generated by Django 5.0.14 on 2026-02-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_interest_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Emoji",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="emoji",
            new_name="icon",
        ),
    ]
