# Generated by Django 5.0.14 on 2026-06-27 13:42

from django.db import migrations
from django.utils.text import slugify


def populate_category_slugs(apps, schema_editor):
    """Generate slugs for existing categories based on their names"""
    Category = apps.get_model("core", "Category")
    for category in Category.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            category.save(update_fields=["slug"])


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration: clear all slugs (approximate reverse)"""
    Category = apps.get_model("core", "Category")
    Category.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_slug"),
    ]

    operations = [
        migrations.RunPython(populate_category_slugs, reverse_populate_slugs),
    ]
