# Generated by Django 5.0.14 on 2026-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizerPaymentConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "collection_type",
                    models.CharField(
                        choices=[("paybill", "Paybill"), ("till", "Till")],
                        help_text="Organizer's M-Pesa collection method",
                        max_length=20,
                    ),
                ),
                ("collection_shortcode", models.CharField(help_text="Paybill number or Till number", max_length=20)),
                (
                    "collection_passkey",
                    models.CharField(
                        help_text="Lipa Na M-Pesa Online Passkey (store encrypted in production)", max_length=255
                    ),
                ),
                (
                    "payout_type",
                    models.CharField(
                        choices=[
                            ("b2c", "Personal M-Pesa"),
                            ("b2b_paybill", "Business Paybill"),
                            ("b2b_till", "Business Till"),
                        ],
                        help_text="How organizer wants to receive payouts",
                        max_length=20,
                    ),
                ),
                (
                    "payout_destination",
                    models.CharField(help_text="Phone number (B2C) or shortcode (B2B)", max_length=20),
                ),
                ("verified", models.BooleanField(default=False, help_text="Admin verified payment config is correct")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organizer Payment Config",
                "verbose_name_plural": "Organizer Payment Configs",
            },
        ),
        migrations.CreateModel(
            name="OrganizerPayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount paid to organizer (order.total - platform_fee)",
                        max_digits=10,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Platform fee deducted from order (denormalized for reporting)",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("frozen", "Frozen"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(help_text="When to process this payout (order.created_at + 24 hours)"),
                ),
                (
                    "mpesa_receipt",
                    models.CharField(
                        blank=True, help_text="M-Pesa receipt from B2C/B2B transaction", max_length=50, null=True
                    ),
                ),
                (
                    "frozen_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why payout was frozen (e.g., 'Event cancelled')",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When payout completed successfully", null=True),
                ),
            ],
            options={
                "verbose_name": "Organizer Payout",
                "verbose_name_plural": "Organizer Payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(default="Unnamed Organizer", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Manually verified by admin before organizer can create events"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="False = organizer role deactivated (soft delete)"),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organizer Profile",
                "verbose_name_plural": "Organizer Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
