# Generated by Django 5.0.14 on 2026-06-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerPaymentInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "collection_type",
                    models.CharField(choices=[("paybill", "Paybill"), ("till_number", "Till Number")], max_length=20),
                ),
                ("collection_short_code", models.CharField(max_length=20)),
                ("collection_passkey", models.CharField(max_length=255)),
                (
                    "payout_type",
                    models.CharField(
                        choices=[
                            ("b2c", "Personal Phone Number"),
                            ("b2b_paybill", "Business Paybill"),
                            ("b2b_till", "Business Till Number"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payout_destination", models.CharField(max_length=20)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerPayoutHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payout_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("b2c", "Personal Phone Number"),
                            ("b2b_paybill", "Business Paybill"),
                            ("b2b_till", "Business Till Number"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payout_destination", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("frozen", "Frozen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("scheduled_for", models.DateTimeField()),
                ("mpesa_receipt", models.CharField(blank=True, max_length=50, null=True)),
                ("frozen_reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="events.event"
                    ),
                ),
            ],
        ),
    ]
