# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizers", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerpayout",
            name="order",
            field=models.ForeignKey(
                help_text="PROTECT: Never auto-delete financial records",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout",
                to="payments.order",
            ),
        ),
    ]
