# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="User can be deleted for GDPR; organizer record survives for financial history",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizerpayout",
            name="organizer",
            field=models.ForeignKey(
                help_text="PROTECT: Never auto-delete financial records",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="organizers.organizerprofile",
            ),
        ),
        migrations.AddField(
            model_name="organizerpaymentconfig",
            name="organizer",
            field=models.OneToOneField(
                help_text="Config has no value without organizer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_config",
                to="organizers.organizerprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="organizerpayout",
            index=models.Index(fields=["organizer", "status"], name="organizers__organiz_b044df_idx"),
        ),
        migrations.AddIndex(
            model_name="organizerpayout",
            index=models.Index(fields=["scheduled_for", "status"], name="organizers__schedul_04b966_idx"),
        ),
        migrations.AddIndex(
            model_name="organizerpayout",
            index=models.Index(fields=["status", "created_at"], name="organizers__status_34bf5b_idx"),
        ),
    ]
