# Generated by Django 5.0.14 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizerprofile",
            name="business_name",
            field=models.CharField(max_length=255),
        ),
    ]
