# Generated by Django 4.2.16 on 2025-11-25 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recommendations/"
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("destination", "Destination"),
                            ("activity", "Activity"),
                            ("experience", "Experience"),
                            ("event", "Event"),
                        ],
                        default="activity",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("best_time_to_visit", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("difficulty_level", models.CharField(blank=True, max_length=50)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("website_url", models.URLField(blank=True)),
                ("booking_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "db_table": "recommendations_recommendation",
                "ordering": ["-popularity_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007AFF", max_length=7)),
            ],
            options={
                "verbose_name": "Recommendation Tag",
                "verbose_name_plural": "Recommendation Tags",
                "db_table": "recommendations_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_recommendation_tags",
            },
        ),
        migrations.CreateModel(
            name="UserRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed", "Viewed"),
                            ("liked", "Liked"),
                            ("saved", "Saved"),
                            ("added_to_bucket", "Added to Bucket"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="recommendations.recommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Recommendation",
                "verbose_name_plural": "User Recommendations",
                "db_table": "recommendations_user_recommendation",
            },
        ),
    ]
