# Generated by Django 4.2.16 on 2025-09-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recommendations/"
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("destination", "Destination"),
                            ("activity", "Activity"),
                            ("experience", "Experience"),
                            ("event", "Event"),
                        ],
                        default="activity",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("best_time_to_visit", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("difficulty_level", models.CharField(blank=True, max_length=50)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("website_url", models.URLField(blank=True)),
                ("booking_url", models.URLField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "db_table": "recommendations_recommendation",
                "ordering": ["-popularity_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007AFF", max_length=7)),
            ],
            options={
                "verbose_name": "Recommendation Tag",
                "verbose_name_plural": "Recommendation Tags",
                "db_table": "recommendations_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed", "Viewed"),
                            ("liked", "Liked"),
                            ("saved", "Saved"),
                            ("added_to_bucket", "Added to Bucket"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="recommendations.recommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Recommendation",
                "verbose_name_plural": "User Recommendations",
                "db_table": "recommendations_user_recommendation",
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="recommendat_user_id_1ee802_idx"
                    ),
                    models.Index(
                        fields=["recommendation"], name="recommendat_recomme_f93e0c_idx"
                    ),
                ],
                "unique_together": {("user", "recommendation", "action")},
            },
        ),
        migrations.CreateModel(
            name="RecommendationTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="recommendations.recommendation",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_relations",
                        to="recommendations.recommendationtag",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_recommendation_tags",
                "unique_together": {("recommendation", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["recommendation_type"], name="recommendat_recomme_1762d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["category"], name="recommendat_categor_65d86c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["location"], name="recommendat_locatio_990579_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="recommendat_is_feat_77449c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["-popularity_score"], name="recommendat_popular_7f1ae2_idx"
            ),
        ),
    ]
