# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007AFF", max_length=7)),
            ],
            options={
                "verbose_name": "Recommendation Tag",
                "verbose_name_plural": "Recommendation Tags",
                "db_table": "recommendations_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
                ("location_name", models.CharField(max_length=200)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("destination", "Destination"),
                            ("activity", "Activity"),
                            ("experience", "Experience"),
                            ("event", "Event"),
                        ],
                        default="activity",
                        max_length=20,
                    ),
                ),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("best_time_to_visit", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("difficulty_level", models.CharField(blank=True, max_length=50)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("website_url", models.URLField(blank=True)),
                ("booking_url", models.URLField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "db_table": "recommendations_recommendation",
                "ordering": ["-popularity_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationTagRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="recommendations.recommendation",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_relations",
                        to="recommendations.recommendationtag",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations_recommendation_tags",
            },
        ),
        migrations.CreateModel(
            name="UserRecommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed", "Viewed"),
                            ("liked", "Liked"),
                            ("saved", "Saved"),
                            ("added_to_bucket", "Added to Bucket"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="recommendations.recommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Recommendation",
                "verbose_name_plural": "User Recommendations",
                "db_table": "recommendations_user_recommendation",
            },
        ),
    ]
