# Generated by Django 5.0.14 on 2026-06-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["recommendation_type"], name="recommendat_recomme_1762d7_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["category"], name="recommendat_categor_65d86c_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["location_name"], name="recommendat_locatio_ae18b7_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["is_featured", "is_active"], name="recommendat_is_feat_77449c_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["-popularity_score"], name="recommendat_popular_7f1ae2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationtagrelation",
            unique_together={("recommendation", "tag")},
        ),
        migrations.AddIndex(
            model_name="userrecommendation",
            index=models.Index(fields=["user", "action"], name="recommendat_user_id_1ee802_idx"),
        ),
        migrations.AddIndex(
            model_name="userrecommendation",
            index=models.Index(fields=["recommendation"], name="recommendat_recomme_f93e0c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userrecommendation",
            unique_together={("user", "recommendation", "action")},
        ),
    ]
