# Generated by Django 5.0.14 on 2026-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
