# Generated by Django 5.0.14 on 2026-02-05 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("recommendations", "0003_alter_recommendation_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recommendation",
            name="recommendat_locatio_990579_idx",
        ),
        migrations.RenameField(
            model_name="recommendation",
            old_name="location",
            new_name="location_name",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="longitude",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["location_name"], name="recommendat_locatio_ae18b7_idx"
            ),
        ),
    ]
