# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MPESATransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "checkout_request_id",
                    models.CharField(help_text="Daraja STK Push unique identifier", max_length=100, unique=True),
                ),
                ("merchant_request_id", models.CharField(max_length=100)),
                (
                    "mpesa_receipt",
                    models.CharField(
                        blank=True, help_text="M-Pesa receipt number (e.g., QGH1234567)", max_length=50, null=True
                    ),
                ),
                (
                    "result_code",
                    models.CharField(
                        blank=True, help_text="Daraja result code (0 = success)", max_length=10, null=True
                    ),
                ),
                (
                    "result_desc",
                    models.CharField(blank=True, help_text="Daraja result description", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "M-Pesa Transaction",
                "verbose_name_plural": "M-Pesa Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ticket price × quantity (base amount before any adjustments)",
                        max_digits=10,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform fee deducted from organizer payout (NOT added to buyer total in Model B)",
                        max_digits=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Final amount buyer pays (equals subtotal in Model B; leaves room for discounts in V2)",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Cannot delete event with existing orders",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
