# Generated by Django 5.0.14 on 2026-06-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="mpesa_transaction", to="payments.order"
            ),
        ),
    ]
