# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Financial record survives user deletion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="order",
            field=models.OneToOneField(
                help_text="Transaction is part of the order lifecycle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mpesa_transaction",
                to="payments.order",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status"], name="payments_or_user_id_0f08a8_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["event", "status"], name="payments_or_event_i_da12f3_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "created_at"], name="payments_or_status_99bb2e_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["idempotency_key"], name="payments_or_idempot_c5a9e0_idx"),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(fields=["checkout_request_id"], name="payments_mp_checkou_a6f836_idx"),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(fields=["result_code"], name="payments_mp_result__996182_idx"),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(fields=["created_at"], name="payments_mp_created_78d6d8_idx"),
        ),
    ]
