# Generated by Django 5.0.14 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When order status changed to 'paid' (triggers 24h payout countdown)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="platform_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Platform fee deducted from organizer payout (NOT added to buyer total in Model B)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Ticket price × quantity (base amount before any adjustments)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Final amount buyer pays (equals subtotal in Model B; leaves room for discounts in V2)",
                max_digits=10,
            ),
        ),
    ]
