# Generated by Django 5.0.14 on 2026-06-04 12:58

import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[("email", "Email"), ("google", "Google SSO")], default="email", max_length=20
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True, help_text="ID from the authentication provider", max_length=255, null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, null=True, verbose_name="last name")),
                ("profile_picture", models.URLField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 hash of verification token", max_length=64, null=True
                    ),
                ),
                ("email_verification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "password_reset_token_hash",
                    models.CharField(blank=True, help_text="SHA-256 hash of reset token", max_length=64, null=True),
                ),
                ("password_reset_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users_user",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "db_table": "users_login_attempt",
                "indexes": [
                    models.Index(fields=["email", "created_at"], name="users_login_email_3a5118_idx"),
                    models.Index(fields=["ip_address", "created_at"], name="users_login_ip_addr_992f6e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("session_token", models.CharField(max_length=500, unique=True)),
                ("device_info", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Session",
                "verbose_name_plural": "Device Sessions",
                "db_table": "users_device_session",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=500, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="users.usersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "users_refresh_token",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "location_name",
                    models.CharField(blank=True, help_text="City, State/Country display name", max_length=100),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                (
                    "last_synced_location_tag",
                    models.CharField(
                        blank=True,
                        default="nairobi",
                        help_text="Derived location tag for editorial scoping (e.g., 'nairobi', 'mombasa')",
                        max_length=100,
                    ),
                ),
                (
                    "search_radius_km",
                    models.PositiveIntegerField(
                        default=50, help_text="Default search radius for nearby events in kilometers"
                    ),
                ),
                ("timezone", models.CharField(blank=True, default="UTC", max_length=50)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("is_onboarding_completed", models.BooleanField(default=False)),
                ("has_skipped_onboarding", models.BooleanField(default=False)),
                ("is_profile_public", models.BooleanField(default=True)),
                ("allow_location_sharing", models.BooleanField(default=True)),
                ("allow_email_notifications", models.BooleanField(default=True)),
                ("allow_push_notifications", models.BooleanField(default=True)),
                ("calendar_integrated", models.BooleanField(default=False)),
                (
                    "calendar_provider",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("google_calendar", "Google Calendar"),
                            ("outlook", "Microsoft Outlook"),
                            ("apple_calendar", "Apple Calendar"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("calendar_sync_token", models.CharField(blank=True, max_length=255, null=True)),
                ("calendar_last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_plan",
                    models.CharField(
                        choices=[("free", "Free"), ("basic", "Basic"), ("premium", "Premium")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("subscription_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_billing_date", models.DateTimeField(blank=True, null=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("auto", "Auto")], default="auto", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User's selected interests for personalization",
                        related_name="users",
                        to="core.interest",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "users_user_profile",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["provider_id"], name="users_user_provide_8a3e60_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["auth_provider"], name="users_user_auth_pr_06709b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["date_joined"], name="users_user_date_jo_064c8f_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["user", "is_active"], name="users_devic_user_id_fb739d_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["created_at"], name="users_devic_created_8e198b_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["user", "is_revoked"], name="users_refre_user_id_3cd07b_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["expires_at"], name="users_refre_expires_b6a3ee_idx"),
        ),
    ]
