# Generated by Django 5.0.14 on 2025-12-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_skipped_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
