# Generated by Django 5.0.14 on 2026-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_has_skipped_onboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
