# Generated by Django 5.0.14 on 2026-02-05 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="home_latitude",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="home_longitude",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_name",
            field=models.CharField(
                blank=True, help_text="City, State/Country display name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
