# Generated by Django 5.0.14 on 2026-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_userprofile_home_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_location_sharing",
            field=models.BooleanField(default=True),
        ),
    ]
