# Generated by Django 5.0.14 on 2026-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_move_interest_to_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_synced_location_tag",
            field=models.CharField(
                blank=True,
                default="nairobi",
                help_text="Derived location tag for editorial scoping (e.g., 'nairobi', 'mombasa')",
                max_length=100,
            ),
        ),
    ]
