# Generated by Django 5.0.14 on 2026-06-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("itinerary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="trips", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["user", "start_date"], name="itinerary_t_user_id_6f383e_idx"),
        ),
    ]
