# Generated by Django 5.0.14 on 2026-06-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="direction",
            field=models.CharField(choices=[("INTERESTED", "Interested"), ("SKIP", "Skip")], max_length=15),
        ),
    ]
