# Generated by Django 5.0.14 on 2026-06-04 13:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketItemLike",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bucket Item Like",
                "verbose_name_plural": "Bucket Item Likes",
                "db_table": "buckets_bucket_item_like",
            },
        ),
        migrations.CreateModel(
            name="BucketItemPhoto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.URLField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Bucket Item Photo",
                "verbose_name_plural": "Bucket Item Photos",
                "db_table": "buckets_bucket_item_photo",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketItemProgress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("progress_percentage", models.PositiveSmallIntegerField()),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Bucket Item Progress",
                "verbose_name_plural": "Bucket Item Progress Updates",
                "db_table": "buckets_bucket_item_progress",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketList",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="My Bucket List", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bucket List",
                "verbose_name_plural": "Bucket Lists",
                "db_table": "buckets_bucket_list",
            },
        ),
        migrations.CreateModel(
            name="BucketItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("location_name", models.CharField(blank=True, max_length=200)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("extreme", "Extreme"),
                        ],
                        default="moderate",
                        max_length=15,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bucket_items",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket Item",
                "verbose_name_plural": "Bucket Items",
                "db_table": "buckets_bucket_item",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketItemComment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "bucket_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="buckets.bucketitem"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="buckets.bucketitemcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket Item Comment",
                "verbose_name_plural": "Bucket Item Comments",
                "db_table": "buckets_bucket_item_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
