# Generated by Django 4.2.16 on 2025-09-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="bucket_items/"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("extreme", "Extreme"),
                        ],
                        default="moderate",
                        max_length=15,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Bucket Item",
                "verbose_name_plural": "Bucket Items",
                "db_table": "buckets_bucket_item",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="My Bucket List", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket List",
                "verbose_name_plural": "Bucket Lists",
                "db_table": "buckets_bucket_list",
            },
        ),
        migrations.CreateModel(
            name="BucketItemProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("progress_percentage", models.PositiveSmallIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="progress_updates/"
                    ),
                ),
                (
                    "bucket_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="buckets.bucketitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket Item Progress",
                "verbose_name_plural": "Bucket Item Progress Updates",
                "db_table": "buckets_bucket_item_progress",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketItemPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="bucket_item_photos/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "bucket_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="buckets.bucketitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket Item Photo",
                "verbose_name_plural": "Bucket Item Photos",
                "db_table": "buckets_bucket_item_photo",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketItemLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bucket_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="buckets.bucketitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_item_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket Item Like",
                "verbose_name_plural": "Bucket Item Likes",
                "db_table": "buckets_bucket_item_like",
            },
        ),
        migrations.CreateModel(
            name="BucketItemComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "bucket_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="buckets.bucketitem",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="buckets.bucketitemcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_item_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucket Item Comment",
                "verbose_name_plural": "Bucket Item Comments",
                "db_table": "buckets_bucket_item_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="bucket_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="buckets.bucketlist",
            ),
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bucket_items",
                to="core.category",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketlist",
            index=models.Index(
                fields=["user", "is_default"], name="buckets_buc_user_id_74acde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketlist",
            index=models.Index(
                fields=["user", "is_active"], name="buckets_buc_user_id_6ee935_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bucketlist",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="bucketitemlike",
            index=models.Index(
                fields=["bucket_item"], name="buckets_buc_bucket__79c836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitemlike",
            index=models.Index(fields=["user"], name="buckets_buc_user_id_a6f1bd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bucketitemlike",
            unique_together={("bucket_item", "user")},
        ),
        migrations.AddIndex(
            model_name="bucketitemcomment",
            index=models.Index(
                fields=["bucket_item", "-created_at"],
                name="buckets_buc_bucket__72dc8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitemcomment",
            index=models.Index(fields=["user"], name="buckets_buc_user_id_b38df1_idx"),
        ),
        migrations.AddIndex(
            model_name="bucketitemcomment",
            index=models.Index(
                fields=["parent"], name="buckets_buc_parent__8ca777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["bucket_list", "is_completed"],
                name="buckets_buc_bucket__944e9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["category"], name="buckets_buc_categor_f5eb2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["priority"], name="buckets_buc_priorit_53deda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["target_date"], name="buckets_buc_target__4bb929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["is_public"], name="buckets_buc_is_publ_b4e802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["location"], name="buckets_buc_locatio_7f0b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["-created_at"], name="buckets_buc_created_ddd266_idx"
            ),
        ),
    ]
