# Generated by Django 4.2.16 on 2025-11-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buckets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucketitemprogress",
            name="bucket_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_updates",
                to="buckets.bucketitem",
            ),
        ),
        migrations.AddField(
            model_name="bucketitemphoto",
            name="bucket_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="buckets.bucketitem",
            ),
        ),
        migrations.AddField(
            model_name="bucketitemlike",
            name="bucket_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="buckets.bucketitem",
            ),
        ),
        migrations.AddField(
            model_name="bucketitemlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_item_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucketitemcomment",
            name="bucket_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="buckets.bucketitem",
            ),
        ),
        migrations.AddField(
            model_name="bucketitemcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="buckets.bucketitemcomment",
            ),
        ),
        migrations.AddField(
            model_name="bucketitemcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_item_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="bucket_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="buckets.bucketlist",
            ),
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bucket_items",
                to="core.category",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketlist",
            index=models.Index(
                fields=["user", "is_default"], name="buckets_buc_user_id_74acde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketlist",
            index=models.Index(
                fields=["user", "is_active"], name="buckets_buc_user_id_6ee935_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bucketlist",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="bucketitemlike",
            index=models.Index(
                fields=["bucket_item"], name="buckets_buc_bucket__79c836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitemlike",
            index=models.Index(fields=["user"], name="buckets_buc_user_id_a6f1bd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bucketitemlike",
            unique_together={("bucket_item", "user")},
        ),
        migrations.AddIndex(
            model_name="bucketitemcomment",
            index=models.Index(
                fields=["bucket_item", "-created_at"],
                name="buckets_buc_bucket__72dc8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitemcomment",
            index=models.Index(fields=["user"], name="buckets_buc_user_id_b38df1_idx"),
        ),
        migrations.AddIndex(
            model_name="bucketitemcomment",
            index=models.Index(
                fields=["parent"], name="buckets_buc_parent__8ca777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["bucket_list", "is_completed"],
                name="buckets_buc_bucket__944e9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["category"], name="buckets_buc_categor_f5eb2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["priority"], name="buckets_buc_priorit_53deda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["target_date"], name="buckets_buc_target__4bb929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["is_public"], name="buckets_buc_is_publ_b4e802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["location"], name="buckets_buc_locatio_7f0b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["-created_at"], name="buckets_buc_created_ddd266_idx"
            ),
        ),
    ]
