# Generated by Django 5.0.14 on 2026-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buckets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucketitem",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bucketitemphoto",
            name="image",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="bucketitemprogress",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
