# Generated by Django 5.0.14 on 2026-02-05 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buckets", "0003_alter_bucketitem_image_alter_bucketitemphoto_image_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bucketitem",
            name="buckets_buc_locatio_7f0b2d_idx",
        ),
        migrations.RenameField(
            model_name="bucketitem",
            old_name="location",
            new_name="location_name",
        ),
        migrations.RemoveField(
            model_name="bucketitem",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="bucketitem",
            name="longitude",
        ),
        migrations.AddField(
            model_name="bucketitem",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="bucketitem",
            index=models.Index(
                fields=["location_name"], name="buckets_buc_locatio_9bd7c0_idx"
            ),
        ),
    ]
