# Generated by Django 5.0.14 on 2026-06-04 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(max_length=100)),
                ("condition", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("icon", models.CharField(blank=True, default="01d", max_length=10)),
                ("latitude", models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "db_table": "insights_weather_data",
                "indexes": [
                    models.Index(fields=["city"], name="insights_we_city_068614_idx"),
                    models.Index(fields=["created_at"], name="insights_we_created_548d3c_idx"),
                ],
            },
        ),
    ]
