# Generated by Django 4.2.16 on 2025-11-25 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("greeting", models.CharField(default="Hello", max_length=100)),
                ("time_of_day", models.CharField(default="morning", max_length=20)),
            ],
            options={
                "verbose_name": "Home Data",
                "verbose_name_plural": "Home Data",
                "db_table": "insights_home_data",
            },
        ),
        migrations.CreateModel(
            name="UserInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_bucket_items", models.PositiveIntegerField(default=0)),
                ("completed_items", models.PositiveIntegerField(default=0)),
                ("yearly_goal", models.PositiveIntegerField(default=12)),
                ("current_city", models.CharField(blank=True, max_length=100)),
                ("next_destination", models.CharField(blank=True, max_length=200)),
                (
                    "days_to_next_trip",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("recent_achievement", models.CharField(blank=True, max_length=200)),
                ("total_countries_visited", models.PositiveIntegerField(default=0)),
                ("total_experiences", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_cost_per_item",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "User Insight",
                "verbose_name_plural": "User Insights",
                "db_table": "insights_user_insight",
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(max_length=100)),
                ("condition", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "db_table": "insights_weather_data",
                "indexes": [
                    models.Index(fields=["city"], name="insights_we_city_068614_idx"),
                    models.Index(
                        fields=["created_at"], name="insights_we_created_548d3c_idx"
                    ),
                ],
            },
        ),
    ]
