# Generated by Django 5.0.14 on 2026-03-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(blank=True, default='01d', max_length=10),
        ),
    ]
