# Generated by Django 5.0.14 on 2026-05-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0005_add_neighborhood_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Neighborhood",
        ),
    ]
