# Generated by Django 5.0.14 on 2026-05-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0006_remove_neighborhood_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserInsight",
        ),
    ]
